export const lazyIconsMapping = {
  "AI/ML": () =>
    import("@/icons/AIML").then((mod) => ({ default: mod.AIMLIcon })),
  "postgres-sql": () =>
    import("@/icons/postgres-sql").then((mod) => ({ default: mod.PostgresSQLIcon })),
  "postgresql": () =>
    import("@/icons/postgres-sql").then((mod) => ({ default: mod.PostgresSQLIcon })),
  "salesforce": () =>
    import("@/icons/salesforce").then((mod) => ({ default: mod.SalesforceIconComponent })),
  "snowflake": () =>
    import("@/icons/snowflake").then((mod) => ({ default: mod.SnowflakeIconComponent })),
  "csv": () =>
    import("@/icons/CSV").then((mod) => ({ default: mod.FileCsvIconComponent })),
  "amazon_s3": () =>
    import("@/icons/AmazonS3").then((mod) => ({ default: mod.AmazonS3IconComponent})),
  "s3": () =>
    import("@/icons/AmazonS3").then((mod) => ({ default: mod.AmazonS3IconComponent})),
  // "filter": () =>
  //   import("@/icons/Filter").then((mod) => ({ default: mod.FilterIconComponent})),
  // "merge": () =>
  //   import("@/icons/Merge").then((mod) => ({ default: mod.MergeIconComponent})),
  "mysql": () =>
    import("@/icons/Mysql").then((mod) => ({ default: mod.MysqlIconComponent })),
  "mssql": () =>
    import("@/icons/MSsql").then((mod) => ({ default: mod.MicrosoftsqlserverIconComponent })),
  "oracle": () =>
    import("@/icons/Oracle").then((mod) => ({ default: mod.OracleIconComponent })),
  "s4hana": () =>
    import("@/icons/SAP-Hana").then((mod) => ({ default: mod.SapIconComponent })),
  "panel-bottom-close": () =>
    import("@/icons/PanelBottomClose").then((mod) => ({ default: mod.PanelBottomCloseIconComponent })),
  "panel-bottom-open": () =>
    import("@/icons/PanelBottomOpen").then((mod) => ({ default: mod.PanelBottomOpenIconComponent })),
  "execute": () =>
    import("@/icons/Play").then((mod) => ({ default: mod.PlayIconComponent })),
  "parquet": () => 
    import("@/icons/Parquet").then((mod) => ({ default: mod.ParquetIconComponent })),
  "dynamodb": () => 
    import("@/icons/Dynamodb/Dynamodb-icon").then((mod) => ({ default: mod.DynamodbIcon })),
  "double-arrow": () => 
    import("@/icons/ArrowDown").then((mod) => ({ default: mod.DoubleArrowIconComponent })),
  "excel": () => 
    import("@/icons/Excel").then((mod) => ({ default: mod.ExcelIconComponent })),
  "redis": () => 
    import("@/icons/Redis").then((mod) => ({ default: mod.RedisIconComponent})),
  "mongodb": () => 
    import("@/icons/MongoDB").then((mod) => ({ default: mod.MongoDBIconComponent})),
  "minio": () =>
    import("@/icons/MinIO").then((mod) => ({ default: mod.MinioIconComponent })),
  "signvio": () =>
    import("@/icons/Signvio").then((mod) => ({ default: mod.SignvioIconComponent })),
  "signavio": () =>
    import("@/icons/Signvio").then((mod) => ({ default: mod.SignvioIconComponent })),
  "elasticsearch": () => 
    import("@/icons/ElasticSearch").then((mod) => ({ default: mod.ElasticSearchIconComponent})),
  "redshift": () => 
    import("@/icons/RedShift").then((mod) => ({ default: mod.RedShiftIconComponent})),
  "clickhouse": () => 
    import("@/icons/ClickHouse").then((mod) => ({ default: mod.ClickHouseIconComponent})),
  "influxdb": () =>
    import("@/icons/InfluxDB").then((mod) => ({ default: mod.InfluxDBIconComponent })),
  "cockroachdb": () => 
    import("@/icons/CockroachDB").then((mod) => ({ default: mod.CockroachDBIconComponent})),  
  "duckdb": () => 
    import("@/icons/DuckDB").then((mod) => ({ default: mod.DuckDBIconComponent})),  
  "singlestore": () => 
    import("@/icons/SingleStore").then((mod) => ({ default: mod.SingleStoreIconComponent})),  
  "add_column": () => 
    import("@/icons/AddColumn").then((mod) => ({ default: mod.AddColumnIconComponent })),
  "drop_column": () => 
    import("@/icons/DeleteColumn").then((mod) => ({ default: mod.DeleteColumnIconComponent })),
  "sftp": () => 
    import("@/icons/SFTP").then((mod) => ({ default: mod.SFTPIconComponent})),
  "blob storage": () => 
    import("@/icons/Blob-Storage").then((mod) => ({ default: mod.BlobStorageIconComponent})),
  blob_storage: () =>
    import("@/icons/Blob-Storage").then((mod) => ({ default: mod.BlobStorageIconComponent})),
  "json": () => 
    import("@/icons/Json").then((mod) => ({ default: mod.JsonIconComponent})),
  "slack": () => 
    import("@/icons/Slack").then((mod) => ({ default: mod.SlackIconComponent})),
  "email": () => 
    import("@/icons/Email").then((mod) => ({ default: mod.EmailIconComponent})),
  "whatsapp": () => 
    import("@/icons/Whatsapp").then((mod) => ({ default: mod.WhatsappIconComponent})),
  "teams": () => 
    import("@/icons/Teams").then((mod) => ({ default: mod.TeamsIconComponent})),
  "sendgrid": () => 
    import("@/icons/Sendgrid").then((mod) => ({ default: mod.SendGridIconComponent})),
  "jira": () => 
    import("@/icons/Jira").then((mod) => ({ default: mod.JiraIconComponent})),
  "dbt": () => 
    import("@/icons/DBT").then((mod) => ({ default: mod.DBTIconComponent})),
  "kafka": () => 
    import("@/icons/Kafka").then((mod) => ({ default: mod.KafkaIconComponent})),
  "bigquery": () => 
    import("@/icons/BigQuery").then((mod) => ({ default: mod.BigQueryIconComponent})),
  "aws lambda": () =>
    import("@/icons/AwsLambda").then((mod) => ({ default: mod.AWSLambdaIconComponent})),
  aws_lambda: () =>
    import("@/icons/AwsLambda").then((mod) => ({ default: mod.AWSLambdaIconComponent})),
  "databricks lakehouse": () =>
    import("@/icons/DataBricksLakehouse").then((mod) => ({ default: mod.DataBricksLakehouseIconComponent})),
  databricks_lakehouse: () =>
    import("@/icons/DataBricksLakehouse").then((mod) => ({ default: mod.DataBricksLakehouseIconComponent})),
  databricks: () =>
    import("@/icons/DataBricksLakehouse").then((mod) => ({ default: mod.DataBricksLakehouseIconComponent})),
  "master_data": () => 
    import("@/icons/MasterData").then((mod) => ({ default: mod.MasterDataIconComponent})),
  "api_connector": () => 
    import("@/icons/APIConnector").then((mod) => ({ default: mod.APIConectorIconComponent})),
  api_gateway: () =>
    import("@/icons/ApiGateway").then((mod) => ({ default: mod.ApiGatewayIconComponent })),
  "concat": () => 
    import("@/icons/Concat").then((mod) => ({ default: mod.ConcatIconComponent})),
  "test_automation": () => 
    import("@/icons/TestAutomation").then((mod) => ({ default: mod.TestAutomationIconComponent})),
  self_validation: () =>
    import("@/icons/TestAutomation").then((mod) => ({ default: mod.TestAutomationIconComponent })),
  "rename_column": () => 
    import("@/icons/Rename").then((mod) => ({ default: mod.RenameIconComponent})),
  "data_validation":()=>
    import("@/icons/DataValidation").then((mod) => ({ default: mod.DataValidationIconComponent})),
  validation: () =>
    import("@/icons/DataValidation").then((mod) => ({ default: mod.DataValidationIconComponent })),
  multisource_validation: () =>
    import("@/icons/DataValidation").then((mod) => ({ default: mod.DataValidationIconComponent })),
  "data_enrichment": () =>
    import("@/icons/DataEnrichment").then((mod) => ({ default: mod.DataEnrichmentIconComponent })),
  deduplication: () =>
    import("@/icons/FuzzyMatch").then((mod) => ({ default: mod.FuzzyMatchIconComponent })),
  "de-duplication": () =>
    import("@/icons/FuzzyMatch").then((mod) => ({ default: mod.FuzzyMatchIconComponent })),
  "fuzzy_match": () =>
    import("@/icons/FuzzyMatch").then((mod) => ({ default: mod.FuzzyMatchIconComponent })),
  "masking":()=>
    import("@/icons/Masking").then((mod) => ({ default: mod.MaskingIconComponent})),
  "sort":()=>
    import("@/icons/Sort").then((mod) => ({ default: mod.SortIconComponent})),
  sort_data: () =>
    import("@/icons/Sort").then((mod) => ({ default: mod.SortIconComponent })),
  "nway_validation":()=>
    import("@/icons/NWay").then((mod) => ({ default: mod.NWayIconComponent})),
  "html":()=>
    import("@/icons/HTML").then((mod) => ({ default: mod.HTMLIconComponent})),
  "aeps":()=>
    import("@/icons/AEPS").then((mod) => ({ default: mod.AEPSIconComponent})),
  "npci":()=>
    import("@/icons/NPCI").then((mod) => ({ default: mod.NPCIIconComponent})),
  "ods":()=>
    import("@/icons/ODS").then((mod) => ({ default: mod.ODSIconComponent})),
  "swift":()=>
    import("@/icons/SWIFT").then((mod) => ({ default: mod.SWIFTIconComponent})),
  "xml":()=>
    import("@/icons/XML").then((mod) => ({ default: mod.XMLIconComponent})),
  "fixed_format":()=>
    import("@/icons/FixedFormat").then((mod) => ({ default: mod.FixedFormatIconComponent})),
  "sfms":()=>
    import("@/icons/SWFMS").then((mod) => ({ default: mod.SFMSIconComponent})),
  "nway_matching":()=>
    import("@/icons/NWAYMatch").then((mod) => ({ default: mod.NWayMatchIconComponent})),
    "report":()=>
    import("@/icons/Reporting").then((mod) => ({ default: mod.ReportingIconComponent})),
  "final_report": () =>
    import("@/icons/Reporting").then((mod) => ({ default: mod.ReportingIconComponent })),
        "custom_scripts":()=>
    import("@/icons/CustomScripts").then((mod) => ({ default: mod.CustomScriptsIconComponent})),
        "carry_forward":()=>
    import("@/icons/CarryOver").then((mod) => ({ default: mod.CarryOverIconComponent})),
        reconciliation_carryover: () =>
    import("@/icons/CarryOver").then((mod) => ({ default: mod.CarryOverIconComponent })),
        "data_collector":()=>
    import("@/icons/DataCollector").then((mod) => ({ default: mod.DataCollectorIconComponent})),
        "splitter":()=>
    import("@/icons/SourceSplitter").then((mod) => ({ default: mod.SourceSplitterIconComponent})),
        "charts":()=>
    import("@/icons/Charts").then((mod) => ({ default: mod.ChartsIconComponent})),
        "trino":()=>
    import("@/icons/Trino").then((mod) => ({ default: mod.TrinoIconComponent})),
  "virtual_db": () =>
    import("@/icons/VirtualDB").then((mod) => ({ default: mod.VirtualDBIconComponent })),
  "subflow_view":()=>
    import("@/icons/subflowview").then((mod) => ({ default: mod.SubflowIconComponent})),
  "pipeline_reference": () =>
    import("@/icons/PipelineReference").then((mod) => ({ default: mod.PipelineIconComponent })),
  "Workflow": () =>
    import("@/icons/WorkflowIcon").then((mod) => ({ default: mod.WorkflowIconComponent })),
  "amqp": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.AmqpIconComponent })),
  "bacnet": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.BacnetIconComponent })),
  "coap": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.CoapIconComponent })),
  "database": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.DatabaseIconComponent })),
  "dnp3": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.Dnp3IconComponent })),
  "ethernet_ip": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.EthernetIpIconComponent })),
  "hart_ip": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.HartIpIconComponent })),
  "iccp_tase2": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.IccpTase2IconComponent })),
  "iec104": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.Iec104IconComponent })),
  "iec61850": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.Iec61850IconComponent })),
  "modbus": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.ModbusIconComponent })),
  "mqtt": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.MqttIconComponent })),
  "opc_ae": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.OpcAeIconComponent })),
  "opc_da": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.OpcDaIconComponent })),
  "opc_hda": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.OpcHdaIconComponent })),
  "opc_ua": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.OpcUaIconComponent })),
  "profinet": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.ProfinetIconComponent })),
  "serial": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.SerialIconComponent })),
  "snmp": () =>
    import("@/icons/ConnectionVault").then((mod) => ({ default: mod.SnmpIconComponent })),
  "ocr": () =>
    import("@/icons/OCR").then((mod) => ({ default: mod.OCRIconComponent })),

};    