import { icons } from "lucide-react";

/** Curated icons shown first (matches common widget / dashboard picks). */
export const WIDGET_ICON_PICKER_ICONS = [
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUpRight",
  "Eye",
  "Play",
  "X",
  "RefreshCw",
  "Menu",
  "Search",
  "Plus",
  "Pencil",
  "Check",
  "Trash2",
  "LineChart",
  "AreaChart",
  "PieChart",
  "BarChart3",
  "Users",
  "Building2",
  "LayoutGrid",
  "Map",
  "MapPin",
  "Puzzle",
  "Settings",
  "Bell",
  "Info",
  "AlertCircle",
  "Lightbulb",
  "Thermometer",
  "Home",
  "Calendar",
  "Clock",
  "Mail",
  "Phone",
  "Star",
  "Heart",
  "Flag",
  "Bookmark",
  "Filter",
  "SlidersHorizontal",
  "Copy",
  "Download",
  "Upload",
  "Share2",
  "Link",
  "ExternalLink",
  "Maximize2",
  "Minimize2",
  "ChevronUp",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "MoreHorizontal",
  "MoreVertical",
  "GripVertical",
  "GripHorizontal",
  "List",
  "Grid3x3",
  "Layers",
  "Box",
  "Package",
  "Database",
  "Server",
  "Cloud",
  "Wifi",
  "Bluetooth",
  "Battery",
  "Power",
  "Zap",
  "Sun",
  "Moon",
  "Droplet",
  "Wind",
  "Activity",
  "Gauge",
  "Target",
  "Crosshair",
  "Compass",
  "Globe",
  "Lock",
  "Unlock",
  "Key",
  "Shield",
  "User",
  "UserPlus",
  "MessageSquare",
  "Send",
  "File",
  "FileText",
  "Folder",
  "Image",
  "Camera",
  "Video",
  "Mic",
  "Monitor",
  "Smartphone",
  "Laptop",
  "Cpu",
  "Code",
  "Terminal",
  "Wrench",
  "Paintbrush",
  "Palette",
  "HelpCircle",
] as const;

export type WidgetIconPickerIconName = (typeof WIDGET_ICON_PICKER_ICONS)[number];

/** Icon grid columns × rows shown before "Show more". */
export const WIDGET_ICON_PICKER_COLUMNS = 10;
export const WIDGET_ICON_PICKER_INITIAL_ROWS = 5;
export const WIDGET_ICON_PICKER_INITIAL_COUNT =
  WIDGET_ICON_PICKER_COLUMNS * WIDGET_ICON_PICKER_INITIAL_ROWS;

let allLucideIconNamesCache: string[] | null = null;

/** Full Lucide library (loaded when user clicks Show more). */
export function getAllLucideIconNames(): string[] {
  if (!allLucideIconNamesCache) {
    allLucideIconNamesCache = Object.keys(icons).sort((a, b) => a.localeCompare(b));
  }
  return allLucideIconNamesCache;
}
